//ERRORES
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const OCULTAR_ERROR = 'OCULTAR_ERROR';
//USUARIOS
export const ERROR_FORMULARIO_ABONADO = 'ERROR_FORMULARIO_ABONADO';
export const CREAR_ABONADO = 'CREAR_ABONADO';
export const DAR_DE_BAJA_ABONADO = 'DAR_DE_BAJA_ABONADO';

export const MODIFICAR_ABONADO = 'MODIFICAR_ABONADO';
export const LISTA_ABONADOS_ACTIVOS = 'LISTA_ABONADOS_ACTIVOS';
export const LISTA_ABONADOS_INACTIVOS = 'LISTA_ABONADOS_INACTIVOS';
//PROVINCIAS
export const LISTA_PROVINCIAS = 'LISTA_PROVINCIAS';
//MUNICIPIOS
export const LISTA_MUNICIPIOS = 'LISTA_MUNICIPIOS';
//BARRIOS
export const LISTA_BARRIOS = 'LISTA_BARRIOS';
//SERVICIOS
export const LISTA_SERVICIOS = 'LISTA_SERVICIOS';
//CONDICIONES IVA
export const LISTA_CONDICIONES_IVA = 'LISTA_CONDICIONES_IVA';