//AUTH
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const MODIFICAR_USUARIO = 'MODIFICAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const LISTA_USUARIOS = 'LISTA_USUARIOS';
export const LISTA_ROLES = 'LISTA_ROLES';
export const CREAR_ROL = 'CREAR_USUARIO';
export const MODIFICAR_ROL = 'MODIFICAR_ROL';
export const ELIMINAR_ROL = 'ELIMINAR_ROL';
export const LISTA_ROLES_USER = 'LISTA_ROLES_USER';
export const LISTA_PERMISOS = 'LISTA_PERMISOS';
export const LISTA_PERMISOS_ROL = 'LISTA_PERMISOS_ROL';

//ABONADOS
export const CREAR_ABONADO = 'CREAR_ABONADO';
export const MODIFICAR_ABONADO = 'MODIFICAR_ABONADO';
export const CAMBIAR_ESTADO_ABONADO = 'CAMBIAR_ESTADO_ABONADO';
export const CAMBIO_DOMICILIO_ABONADO = 'CAMBIO_DOMICILIO_ABONADO';
export const CAMBIO_SERVICIO_ABONADO = 'CAMBIO_SERVICIO_ABONADO';
export const LISTA_ABONADOS = 'LISTA_ABONADOS';
export const LISTA_ABONADOS_ACTIVOS = 'LISTA_ABONADOS_ACTIVOS';
export const LISTA_ABONADOS_INSCRIPTOS = 'LISTA_ABONADOS_INSCRIPTOS';
export const LISTA_ABONADOS_INACTIVOS = 'LISTA_ABONADOS_INACTIVOS';
export const LISTA_DOMICILIOS_ABONADO = 'LISTA_DOMICILIOS_ABONADO';
export const LISTA_SERVICIOS_ABONADO = 'LISTA_SERVICIOS_ABONADO';
export const LISTA_PAGOS_ABONADO = 'LISTA_PAGOS_ABONADO';
export const LISTA_DETALLES_PAGO_ABONADO = 'LISTA_DETALLES_PAGO_ABONADO';
//PAGOS
export const CREAR_PAGO = 'CREAR_PAGO';
export const TRAER_PAGO = 'TRAER_PAGO';
export const ELIMINAR_DETALLE_PAGO = 'ELIMINAR_DETALLE_PAGO';
//BARRIOS
export const LISTA_BARRIOS = 'LISTA_BARRIOS';
export const CREAR_BARRIO = 'CREAR_BARRIO';
export const EDITAR_BARRIO = 'EDITAR_BARRIO';
export const ELIMINAR_BARRIO = 'ELIMINAR_BARRIO';
//CONDICIONES IVA
export const LISTA_CONDICIONES_IVA = 'LISTA_CONDICIONES_IVA';
//MUNICIPIOS
export const LISTA_MUNICIPIOS = 'LISTA_MUNICIPIOS';
export const CREAR_MUNICIPIO = 'CREAR_MUNICIPIO';
export const EDITAR_MUNICIPIO = 'EDITAR_MUNICIPIO';
export const ELIMINAR_MUNICIPIO = 'ELIMINAR_MUNICIPIO';
//PROVINCIAS
export const LISTA_PROVINCIAS = 'LISTA_PROVINCIAS';
//SERVICIOS
export const LISTA_SERVICIOS = 'LISTA_SERVICIOS';
export const CREAR_SERVICIO = 'CREAR_SERVICIO';
export const EDITAR_SERVICIO = 'EDITAR_SERVICIO';
export const ELIMINAR_SERVICIO = 'ELIMINAR_SERVICIO';
//ONUS
export const TRAER_ONU = 'TRAER_ONU';
export const LISTA_ONUS = 'LISTA_ONUS';
export const CREAR_ONU = 'CREAR_ONU';
export const EDITAR_ONU = 'EDITAR_ONU';
export const ELIMINAR_ONU = 'ELIMINAR_ONU';
//MODELOS ONU
export const LISTA_MODELOS_ONU = 'LISTA_MODELOS_ONU';
export const CREAR_MODELO_ONU = 'CREAR_MODELO_ONU';
export const EDITAR_MODELO_ONU = 'EDITAR_MODELO_ONU';
export const ELIMINAR_MODELO_ONU = 'ELIMINAR_MODELO_ONU';
//MEDIOS DE PAGO
export const LISTA_MEDIOS_DE_PAGO = 'LISTA_MEDIOS_DE_PAGO';